[build]
buildCommand = "pip install -r requirements.txt && pip install gunicorn && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && python -m gunicorn washy.wsgi:application --bind 0.0.0.0:$PORT"